blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://libreaccounting.org/forum
    about: 'For ideas or feature requests, start a new discussion'
  - name: Support, help, and other
    url: https://libreaccounting.org/support
    about: 'This repository is only for reporting bugs'
  - name: Documentation
    url: https://github.com/libre-accounting/docs
    about: For documentation improvements, open a pull request at the libre-accounting/docs repository
