version: '3.7'

services:

  libre-accounting:
    container_name: libre-accounting
    build:
      dockerfile: fpm.Dockerfile
      context: .
    volumes:
      - libre-accounting-data:/var/www/html
    restart: unless-stopped
    env_file:
      - env/run.env
    environment:
      - LIBRE_ACCOUNTING_SETUP
    depends_on:
      - libre-accounting-db

  libre-accounting-proxy:
    image: nginx:1.19.0
    ports:
      - 8080:80
    depends_on:
      - libre-accounting
    volumes:
      - libre-accounting-data:/var/www/html
      - ./nginx/templates:/etc/nginx/templates

  libre-accounting-db:
    container_name: libre-accounting-db
    image: mariadb
    volumes:
      - libre-accounting-db:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - env/db.env

volumes:
  libre-accounting-data:
  libre-accounting-db:
